### PR TITLE
fix net_disc gradient bug

### PR DESCRIPTION
**Pull request by onepeachbiubiubiu**
Related to[ this issue](https://github.com/GaParmar/img2img-turbo/issues/56).

### CODE REVIEW

**Comment by Feynman1999** [comment]
I think in https://github.com/GaParmar/img2img-turbo/blob/573dfdd3b1cb6caf6a3c69dabe137200eab26f3c/src/train_pix2pix_turbo.py#L217 
There is also this issue. Strangely, theoretically,  this bug would have an impact on the results? Why do the results in the paper look good

**Comment by GaParmar** [comment]
This bug wasnt there in the model trained for the results in the paper. I think this got introduced when I was cleaning up the repo. 
-Gaurav

**Comment by tfriedel** [comment]
I tried this fix, but I still observe the issue that horses will stay horses and not look like zebras in the slightest.
I think there's probably more changes needed. @GaParmar do you maybe have the source from before the cleanup?

**Comment by tfriedel** [comment]
@Yuxinn-J I have tried with the original version, with this fix and some more fixes by myself, but all were unsuccessful in reproducing the Zebra results.

**Comment by WebsheetPlugin** [comment]
Do I get it right that the Zebra case is not working for anyone? @GaParmar, maybe write that on the main page, as people might be wasting resources while trying to train this or other cases... 

Is there some working version to train CycleGan unpaired?

**Comment by GaParmar** [comment]
I looked into the training issue today. The culprit seems to be mixed precision training. 
I think you will obtain much better results once you disable mixed-precision training. 

Cheers,
Gaurav

**Pull request merged**
